name: extension_data
description: Dart extensions and extension Data. Include base64Encode、base58Encode、hexEncode and Base58Data、Base64Data、HexData.
version: 1.0.1
homepage: https://github.com/kecson/extension_data

topics:
  - utils
  - extensions

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  convert: ^3.1.2
  decimal: ^3.0.2

dev_dependencies:
  test: ^1.25.8
  lints: ^5.0.0

