name: extension_data
description: Dart extensions and extension Data. Include base64Encode、base58Encode、hexEncode and Base58Data、Base64Data、HexData.
version: 1.0.0
homepage: https://github.com/kecson/extension_data

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  convert: ^3.1.1
  decimal: ^2.3.3

dev_dependencies:
  test: ^1.16.0
  lints: ^1.0.1

